# Generated by Django 3.2.7 on 2021-09-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_user_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.AddField(
            model_name='user',
            name='full_address',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='user',
            name='passion',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
